package org.javacc;

/* Generated By:JavaCC: Do not edit this line. GlimmrParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GlimmrParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITESPACE = 1;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 5;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 6;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 7;
  /** RegularExpression Id. */
  int BOOLEAN = 9;
  /** RegularExpression Id. */
  int BREAK = 10;
  /** RegularExpression Id. */
  int WHEN = 11;
  /** RegularExpression Id. */
  int IS = 12;
  /** RegularExpression Id. */
  int CONTINUE = 13;
  /** RegularExpression Id. */
  int NUMBER = 14;
  /** RegularExpression Id. */
  int STRING = 15;
  /** RegularExpression Id. */
  int Unit = 16;
  /** RegularExpression Id. */
  int ELSE = 17;
  /** RegularExpression Id. */
  int FN = 18;
  /** RegularExpression Id. */
  int WHERE = 19;
  /** RegularExpression Id. */
  int TYPE = 20;
  /** RegularExpression Id. */
  int FALSE = 21;
  /** RegularExpression Id. */
  int IMPORT = 22;
  /** RegularExpression Id. */
  int TRUE = 23;
  /** RegularExpression Id. */
  int LOOP = 24;
  /** RegularExpression Id. */
  int LET = 25;
  /** RegularExpression Id. */
  int IN = 26;
  /** RegularExpression Id. */
  int IF = 27;
  /** RegularExpression Id. */
  int MODULE = 28;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 29;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 30;
  /** RegularExpression Id. */
  int HEX_LITERAL = 31;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 32;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 33;
  /** RegularExpression Id. */
  int EXPONENT = 34;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 35;
  /** RegularExpression Id. */
  int STRING_LITERAL = 36;
  /** RegularExpression Id. */
  int IDENTIFIER = 37;
  /** RegularExpression Id. */
  int LETTER = 38;
  /** RegularExpression Id. */
  int PART_LETTER = 39;
  /** RegularExpression Id. */
  int LPAREN = 40;
  /** RegularExpression Id. */
  int RPAREN = 41;
  /** RegularExpression Id. */
  int LBRACE = 42;
  /** RegularExpression Id. */
  int RBRACE = 43;
  /** RegularExpression Id. */
  int LBRACKET = 44;
  /** RegularExpression Id. */
  int RBRACKET = 45;
  /** RegularExpression Id. */
  int SEMICOLON = 46;
  /** RegularExpression Id. */
  int COMMA = 47;
  /** RegularExpression Id. */
  int DOT = 48;
  /** RegularExpression Id. */
  int ASSIGN = 49;
  /** RegularExpression Id. */
  int GT = 50;
  /** RegularExpression Id. */
  int LT = 51;
  /** RegularExpression Id. */
  int BANG = 52;
  /** RegularExpression Id. */
  int TILDE = 53;
  /** RegularExpression Id. */
  int HOOK = 54;
  /** RegularExpression Id. */
  int COLON = 55;
  /** RegularExpression Id. */
  int EQ = 56;
  /** RegularExpression Id. */
  int LE = 57;
  /** RegularExpression Id. */
  int GE = 58;
  /** RegularExpression Id. */
  int NE = 59;
  /** RegularExpression Id. */
  int SC_OR = 60;
  /** RegularExpression Id. */
  int SC_AND = 61;
  /** RegularExpression Id. */
  int INCR = 62;
  /** RegularExpression Id. */
  int DECR = 63;
  /** RegularExpression Id. */
  int PLUS = 64;
  /** RegularExpression Id. */
  int MINUS = 65;
  /** RegularExpression Id. */
  int STAR = 66;
  /** RegularExpression Id. */
  int SLASH = 67;
  /** RegularExpression Id. */
  int BIT_AND = 68;
  /** RegularExpression Id. */
  int BIT_OR = 69;
  /** RegularExpression Id. */
  int XOR = 70;
  /** RegularExpression Id. */
  int REM = 71;
  /** RegularExpression Id. */
  int LSHIFT = 72;
  /** RegularExpression Id. */
  int RSIGNEDSHIFT = 73;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFT = 74;
  /** RegularExpression Id. */
  int PLUSASSIGN = 75;
  /** RegularExpression Id. */
  int MINUSASSIGN = 76;
  /** RegularExpression Id. */
  int STARASSIGN = 77;
  /** RegularExpression Id. */
  int SLASHASSIGN = 78;
  /** RegularExpression Id. */
  int ANDASSIGN = 79;
  /** RegularExpression Id. */
  int ORASSIGN = 80;
  /** RegularExpression Id. */
  int XORASSIGN = 81;
  /** RegularExpression Id. */
  int REMASSIGN = 82;
  /** RegularExpression Id. */
  int LSHIFTASSIGN = 83;
  /** RegularExpression Id. */
  int RSIGNEDSHIFTASSIGN = 84;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFTASSIGN = 85;
  /** RegularExpression Id. */
  int HASH = 86;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_SINGLE_LINE_COMMENT = 1;
  /** Lexical state. */
  int IN_FORMAL_COMMENT = 2;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "\"//\"",
    "<token of kind 3>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 8>",
    "\"Boolean\"",
    "\"break\"",
    "\"when\"",
    "\"is\"",
    "\"continue\"",
    "\"Number\"",
    "\"String\"",
    "\"Unit\"",
    "\"else\"",
    "\"fn\"",
    "\"where\"",
    "\"type\"",
    "\"false\"",
    "\"import\"",
    "\"true\"",
    "\"loop\"",
    "\"let\"",
    "\"in\"",
    "\"if\"",
    "\"module\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<PART_LETTER>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\">>\"",
    "\">>>\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"#\"",
  };

}
